// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/adminko" | "/adminko/sources"
type AppRouteHandlerRoutes = "/api/admin/auth/login" | "/api/admin/auth/logout" | "/api/admin/sources" | "/api/admin/sources/[id]" | "/api/admin/sources/[id]/import" | "/api/admin/sources/test" | "/api/health" | "/api/import"
type PageRoutes = never
type LayoutRoutes = "/" | "/adminko" | "/adminko/sources"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/adminko": {}
  "/adminko/sources": {}
  "/api/admin/auth/login": {}
  "/api/admin/auth/logout": {}
  "/api/admin/sources": {}
  "/api/admin/sources/[id]": { "id": string; }
  "/api/admin/sources/[id]/import": { "id": string; }
  "/api/admin/sources/test": {}
  "/api/health": {}
  "/api/import": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/adminko": never
  "/adminko/sources": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
